Feature-initial
RRusakou/MLM_System pull request #1
Opened 2022-07-19 14:43 UTC by RRusakou

2022-07-19 18:20 UTC, kuriloalexey requested changes

2022-07-19 18:20 UTC, kuriloalexey commented on test/MLMSystemTest.js
> +    expect(mlmSystem.address).to.be.properAddress;
почему юзаешь именно `properAddress`?

2022-07-19 18:20 UTC, kuriloalexey commented on test/MLMSystemTest.js
> +    expect(balance == 0);
нужно переписать тесты все

2022-07-19 18:20 UTC, kuriloalexey commented on contracts/MLMSystem.sol
> +pragma solidity ^0.8.8;
версия

2022-07-19 18:20 UTC, kuriloalexey commented on contracts/MLMSystem.sol
> +    uint8 constant feePercents = 5;
константы большими буквами

2022-07-19 18:20 UTC, kuriloalexey commented on contracts/MLMSystem.sol
> +        }
сделать динамически

2022-07-19 18:20 UTC, kuriloalexey commented on contracts/MLMSystem.sol
> +        uint currentBalance = getBalance(_member);
1 ether

2022-07-19 18:20 UTC, kuriloalexey commented on contracts/MLMSystem.sol
> +        }
динамически

2022-07-19 18:20 UTC, kuriloalexey commented on contracts/MLMSystem.sol
> +    }
Order of Functions[](https://docs.soliditylang.org/en/develop/style-guide.html#order-of-functions)

2022-07-19 18:20 UTC, kuriloalexey commented on test/MLMSystemTest.js
> +    expect(mlmSystem.address).to.be.properAddress;
почему `properAddress`?

2022-07-19 18:20 UTC, kuriloalexey commented on test/MLMSystemTest.js
> +    expect(balance == 0);
нужно будет переписать тесты

2022-07-19 18:20 UTC, kuriloalexey commented on package.json
> +    "buffer-xor": "^2.0.2",
по-моему слишком много зависимостей

2022-07-19 18:20 UTC, kuriloalexey commented
название ветки

2022-07-20 08:55 UTC, RRusakou commented on test/MLMSystemTest.js
> +    expect(mlmSystem.address).to.be.properAddress;
Не совсем правильно написал описание к тесту. properAddress вроде как проверяет правильный ли общий вид адреса и проверяет не равен ли он нулевому. Других методов на проверку правильности адреса я не нашел

2022-07-20 08:55 UTC, RRusakou commented on test/MLMSystemTest.js
> +    expect(balance == 0);
Прям все-все? Тогда не совсем понимаю что не так во всех тестах

2022-07-20 15:30 UTC, kuriloalexey requested changes

2022-07-20 15:30 UTC, kuriloalexey commented on test/MLMSystemTest.js
> +    await mlmSystem.connect(acc1)["signUp()"]();
почему ты испольузешь через [`"signUp()"]`?

2022-07-20 15:30 UTC, kuriloalexey commented on contracts/MLMSystem.sol
> +        }
интересная логика
а если потом комиссия измениться?
 то это придется полностью переписывать

2022-07-21 08:29 UTC, RRusakou commented on test/MLMSystemTest.js
> +    await mlmSystem.connect(acc1)["signUp()"]();
У меня есть перегруженные функции. Регистрация для юзера без реферера и с реферером. Их вызов осуществляется таким образом...

2022-08-02 13:27 UTC, kuriloalexey commented
название ветки

2022-08-02 13:29 UTC, kuriloalexey requested changes

2022-08-02 13:29 UTC, kuriloalexey commented on contracts/MLMSystem.sol
> +
Order of Functions

2022-08-02 13:29 UTC, kuriloalexey commented on contracts/MLMSystem.sol
> +
https://docs.soliditylang.org/en/develop/style-guide.html#order-of-functions

2022-08-02 20:05 UTC, kuriloalexey commented
название ветки

2022-08-03 09:51 UTC, closed without merging